[package]
name = "stretch"
version = "0.1.2"
authors = ["Emil Sjölander <emil@visly.app>"]
edition = "2018"
include = ["src/**/*", "Cargo.toml"]
description = "High performance & cross-platform Flexbox implementation"
repository = "https://github.com/vislyhq/stretch"
readme = "README.md"
keywords = ["ios", "android", "cross-platform", "layout", "flexbox"]
categories = ["gui"]
license = "MIT"
license-file = "LICENSE"

[badges]
circle-ci = { repository = "vislyhq/stretch", branch = "master" }
maintenance = { status = "experimental" }

[dependencies]
ref_eq = "1.0.0"

[dev-dependencies]
criterion = "0.2"

[profile.release]
lto = true
panic = 'abort'

[[bench]]
name = "generated"
harness = false
