version: 2

jobs:
  core:
    docker:
      - image: circleci/rust:1.34

    steps:
      - checkout

      - restore_cache:
          key: target-cache

      - run: rustc --version; cargo --version; rustup --version
      - run: rustup component add rustfmt
      - run: rustup component add clippy
      - run: cargo fmt -- --check
      - run: cargo test
      - run: cargo clippy
      - run: cargo bench

      - save_cache:
          key: target-cache
          paths:
            - ~/.cargo
            - ./target

  ios:
    macos:
      xcode: "10.0.0"

    steps:
      - checkout
      - run: cd bindings/swift && xcodebuild test -workspace Example/StretchKit.xcworkspace -scheme StretchKit -destination 'platform=iOS Simulator,name=iPhone XR,OS=12.0'

  js:
    docker:
      - image: circleci/rust:1.34-node-browsers

    steps:
      - checkout

      - restore_cache:
          key: js-target-cache

      - run: rustc --version; cargo --version; rustup --version
      - run: rustup component add rustfmt
      - run: rustup component add clippy
      - run: cargo install wasm-pack
      - run: cd bindings/js && cargo fmt -- --check
      - run: cd bindings/js && wasm-pack test --node
      - run: cd bindings/js && cargo clippy

      - save_cache:
          key: js-target-cache
          paths:
            - ~/bindings/js/.cargo
            - ./bindings/js/target

workflows:
  version: 2
  test_all:
    jobs:
      - core
      - ios
      - js

